name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  flutter_native_splash: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    
flutter_native_splash:
  color: "#42a5f5"
  image: assets/icon.png
  android: true
  ios: true
  android_12:  # Configuración para Android 12+
    image: assets/icon.png
    color: "#42a5f5"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#42a5f5"  # Color de fondo para íconos adaptables